### ISSUE TITLE
Responses

### ISSUE THREAD

**Issue by ManuelLevi** [MichaelSolati/typeform-python-sdk#6]
Couldn't find how to get the responses, so I've added `get_responses` function to class `Forms`

The code reads like this:
```
 def get_responses(self, uid: str) -> dict:
        """Retrieves the results"""
        return self.__client.request('get', '/forms/%s/responses' % uid)
```

Problem is, this does not deal with pagination and will not work with more than 25 answers according to [the documentation.](https://developer.typeform.com/responses/reference/retrieve-responses/)

**Comment by MichaelSolati** [comment]
I can give this some love today and try to get out the responses functionality =D

**Comment by ManuelLevi** [comment]
That would be great!

**Comment by MichaelSolati** [comment]
Kept on having build issues, but version 1.1.0 has responses and is deployed on [pypi](https://pypi.org/project/typeform/)!
